services:

  web:
    image: lscr.io/linuxserver/swag:5.6.0
    container_name: web
    hostname: web
    cap_add:
      - NET_ADMIN
    security_opt:
      - no-new-privileges:true
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Amsterdam
      - URL=timsdomain.duckdns.org
      - VALIDATION=duckdns
      - CERTPROVIDER=zerossl
      - EMAIL=${ZERO_SSL_EMAIL}
      - SUBDOMAINS=wildcard
      - DUCKDNSTOKEN=${DUCKDNS_TOKEN}
      - DOCKER_MODS=linuxserver/mods:swag-dashboard|linuxserver/mods:swag-dbip
    volumes:
      - /home/tim/config/swag:/config
    ports:
      - 443:443
      - 80:80
      - 81:81
    networks:
      - proxy-net
      - media-net
      - monitoring-net
    restart: unless-stopped

  wg-easy:
    image: ghcr.io/wg-easy/wg-easy:15.3.0
    container_name: wg-easy
    networks:
      wg:
        ipv4_address: 10.42.42.42
        ipv6_address: fdcc:ad94:bacf:61a3::2a
      proxy-net: {}
    volumes:
      - /home/tim/config/wireguard:/etc/wireguard
      - /lib/modules:/lib/modules:ro
    ports:
      - "51820:51820/udp"
      - "127.0.0.1:51821:51821/tcp"
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    security_opt:
      - no-new-privileges:true
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.src_valid_mark=1
      - net.ipv6.conf.all.disable_ipv6=0
      - net.ipv6.conf.all.forwarding=1
      - net.ipv6.conf.default.forwarding=1

  authelia:
    image: ghcr.io/authelia/authelia:4.39.19
    container_name: authelia
    hostname: authelia
    user: "1000:1000"
    depends_on:
      - web
    environment:
      - TZ=Europe/Amsterdam
    expose:
      - 9091
    volumes:
      - /home/tim/config/authelia:/config
    networks:
      - proxy-net
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped

  gluetun:
    image: ghcr.io/qdm12/gluetun:v3.41.1
    container_name: gluetun
    hostname: gluetun
    cap_add:
      - NET_ADMIN
    security_opt:
      - no-new-privileges:true
    devices:
      - /dev/net/tun:/dev/net/tun
    environment:
      - VPN_SERVICE_PROVIDER=nordvpn
      - VPN_TYPE=wireguard
      - SERVER_COUNTRIES=Netherlands
      - SERVER_CITIES=Amsterdam
      # Wireguard:
      - WIREGUARD_PRIVATE_KEY=${NORDVPN_TOKEN}
      - TZ=Europe/Amsterdam
      # Server list updater
      # See https://github.com/qdm12/gluetun-wiki/blob/main/setup/servers.md#update-the-vpn-servers-list
      - UPDATER_PERIOD=24h
    volumes:
      - /home/tim/config/gluetun:/gluetun
    ports:
      - 8888:8888/tcp # HTTP proxy
      - 8388:8388/tcp # Shadowsocks
      - 8388:8388/udp # Shadowsocks
      - 9091:9091 # Transmission
      - 51413:51413 # Transmission
      - 51413:51413/udp # Transmission
      - 8090:8090
      - 8480:8080 # SabNZB
    networks:
      - media-net
    restart: unless-stopped

  homeassistant:
    image: ghcr.io/home-assistant/home-assistant:2026.5.4
    container_name: homeassistant
    hostname: homeassistant
    cap_add:
      - NET_ADMIN
      - NET_RAW
    depends_on:
      - web
      - transmission
      - influxdb
      - grafana
      - telegraf
    healthcheck:
      test: ["CMD", "curl", "-s", "http://localhost:8123"]
      interval: 5s
      timeout: 3s
      retries: 15
    privileged: true
    devices:
      # - /dev/ttyAMA0
      - /dev/ttyACM0
    environment:
      - TZ=Europe/Amsterdam
    volumes:
      - /home/tim/config/homeassistant:/config
      - /run/dbus:/run/dbus:ro
    network_mode: host
    restart: unless-stopped

  esphome:
    container_name: esphome
    image: ghcr.io/esphome/esphome:2026.5.1
    volumes:
      - /home/tim/config/esphome/config:/config
    environment:
      - TZ=Europe/Amsterdam
    restart: unless-stopped
    privileged: true
    network_mode: host

      #  zigbee2mqtt:
      #    image: koenkk/zigbee2mqtt
      #    container_name: zigbee2mqtt
      #    devices:
      #      - /dev/ttyACM0
      #    environment:
      #      - TZ=Europe/Amsterdam
      #    volumes:
      #      - /home/tim/config/zigbee2mqtt:/app/data
      #      - /run/udev:/run/udev:ro
      #    ports:
      #      - 8580:8080
      #    networks:
      #      - media-net
      #    restart: unless-stopped
      #
      #  mosquitto:
      #    image: eclipse-mosquitto:2.0
      #    container_name: mosquitto
      #    command: "mosquitto -c /mosquitto-no-auth.conf"
      #    volumes:
      #      - /home/tim/config/mosquitto:/mosquitto
      #    ports:
      #      - 1883:1883
      #      - 9001:9001
      #    networks:
      #      - media-net
      #    restart: unless-stopped

  influxdb:
    image: influxdb:2.9.1
    container_name: influxdb
    hostname: influxdb
    depends_on:
      - web
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=${INFLUXDB_USER}
      - DOCKER_INFLUXDB_INIT_PASSWORD=${INFLUXDB_USER_PASSWORD}
      - DOCKER_INFLUXDB_INIT_ORG=home
      - DOCKER_INFLUXDB_INIT_BUCKET=home-assistant
    volumes:
      - /home/tim/config/influxdb2:/var/lib/influxdb2
    ports:
      - "127.0.0.1:8086:8086"
    networks:
      - monitoring-net
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped

  telegraf:
    image: telegraf:1.38.4
    container_name: telegraf
    hostname: telegraf
    user: telegraf:996 #Ensure docker group ID is correct
    privileged: true
    depends_on:
      - web
      - influxdb
    environment:
      - HOST_PROC=/hostfs/proc
      - HOST_MOUNT_PREFIX=/hostfs
      - TELEGRAF_INFLUXDB_TOKEN=${TELEGRAF_INFLUXDB_TOKEN}
      - TELEGRAF_INFLUXDB_ORG=${TELEGRAF_INFLUXDB_ORG}
      - TELEGRAF_INFLUXDB_BUCKET=${TELEGRAF_INFLUXDB_BUCKET}
    volumes:
      - /:/hostfs:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./services/telegraf/telegraf.conf:/etc/telegraf/telegraf.conf:ro
    networks:
      - monitoring-net
    restart: unless-stopped

  grafana:
    image: grafana/grafana:13.0.1
    container_name: grafana
    hostname: grafana
    user: "472:472"
    depends_on:
      - web
      - telegraf
    volumes:
      - /home/tim/config/grafana:/var/lib/grafana
    ports:
      - "127.0.0.1:3000:3000"
    networks:
      - monitoring-net
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped

  transmission:
    image: linuxserver/transmission:4.1.1
    container_name: transmission
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Amsterdam
      - USER=${TRANSMISSION_USERNAME}
      - PASS=${TRANSMISSION_PASSWORD}
    volumes:
      - /home/tim/config/transmission:/config
      - /home/tim/nas/data/torrents:/data/torrents
    network_mode: "service:gluetun"
    restart: unless-stopped

  sabnzbd:
    image: lscr.io/linuxserver/sabnzbd:5.0.3
    container_name: sabnzbd
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Amsterdam
    volumes:
      - /home/tim/config/sabnzbd:/config
      - /home/tim/nas/data/usenet:/data/usenet
    network_mode: "service:gluetun"
    restart: unless-stopped

  sonarr-4k:
    image: linuxserver/sonarr:4.0.17
    container_name: sonarr-4k
    hostname: sonarr-4k
    depends_on:
      - web
      - prowlarr
      - sabnzbd
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Amsterdam
    volumes:
      - /home/tim/config/sonarr-4k:/config
      - /home/tim/nas/data:/data
    expose:
      - 8989
    networks:
      - media-net
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped

  sonarr:
    image: linuxserver/sonarr:4.0.17
    container_name: sonarr
    hostname: sonarr
    depends_on:
      - web
      - prowlarr
      - transmission
      - sabnzbd
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Amsterdam
    volumes:
      - /home/tim/config/sonarr:/config
      - /home/tim/nas/data:/data
    expose:
      - 8989
    networks:
      - media-net
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped

  radarr-4k:
    image: linuxserver/radarr:6.1.1
    container_name: radarr-4k
    hostname: radarr-4k
    depends_on:
      - web
      - prowlarr
      - sabnzbd
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Amsterdam
    volumes:
      - /home/tim/config/radarr-4k:/config
      - /home/tim/nas/data:/data
    expose:
      - 7878
    networks:
      - media-net
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped

  radarr:
    image: linuxserver/radarr:6.1.1
    container_name: radarr
    hostname: radarr
    depends_on:
      - web
      - prowlarr
      - transmission
      - sabnzbd
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Amsterdam
    volumes:
      - /home/tim/config/radarr:/config
      - /home/tim/nas/data:/data
    expose:
      - 7878
    networks:
      - media-net
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped

  readarr:
    image: lscr.io/linuxserver/readarr:0.4.19-nightly
    container_name: readarr
    hostname: readarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Amsterdam
    volumes:
      - /home/tim/config/readarr:/config
      - /home/tim/nas/data:/data
    expose:
      - 8787
    networks:
      - media-net
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped

  lidarr:
    image: lscr.io/linuxserver/lidarr:3.1.2-nightly
    container_name: lidarr
    hostname: lidarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Amsterdam
    volumes:
      - /home/tim/config/lidarr:/config
      - /home/tim/nas/data:/data
    expose:
      - 8686
    networks:
      - media-net
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped

  prowlarr:
    image: lscr.io/linuxserver/prowlarr:2.4.0-nightly
    container_name: prowlarr
    hostname: prowlarr
    depends_on:
      - web
      - flaresolverr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Amsterdam
    volumes:
      - /home/tim/config/prowlarr:/config
    expose:
      - 9696
    networks:
      - media-net
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped

  audiobookshelf:
    image: ghcr.io/advplyr/audiobookshelf:2.35.0
    container_name: audiobookshelf
    hostname: audiobookshelf
    environment:
      - TZ=Europe/Amsterdam
      - PORT=13378
    expose:
      - 13378
    volumes:
      - /home/tim/nas/data/media/audio/audiobooks:/audiobooks
      - /home/tim/nas/data/media/audio/podcasts:/podcasts
      - /home/tim/config/audiobookshelf:/config
      - /home/tim/nas/data/media/audiobookshelf/metadata:/metadata
    networks:
      - media-net
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped

  flaresolverr:
    image: ghcr.io/flaresolverr/flaresolverr:v3.4.6
    container_name: flaresolverr
    hostname: flaresolverr
    environment:
      - LOG_LEVEL=${LOG_LEVEL:-info}
      - LOG_HTML=${LOG_HTML:-false}
      - CAPTCHA_SOLVER=${CAPTCHA_SOLVER:-none}
      - TZ=Europe/Amsterdam
    expose:
      - 8191
    networks:
      - media-net
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped

  plex:
    image: linuxserver/plex:1.43.2
    container_name: plex
    hostname: plex
    depends_on:
      - web
      - sonarr
      - radarr
    environment:
      - PUID=1000
      - PGID=1000
      - VERSION=docker
    volumes:
      - /home/tim/config/plex:/config
      - /home/tim/nas/data/media:/data/media
      - /tmp/transcoding:/tmp/transcoding
    network_mode: host
    restart: unless-stopped

  tautulli:
    image: ghcr.io/tautulli/tautulli:v2.17.1
    container_name: tautulli
    hostname: tautulli
    depends_on:
      - plex
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Amsterdam
    volumes:
      - /home/tim/config/tautulli:/config
    expose:
      - 8181
    networks:
      - media-net
      - monitoring-net
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped

  notifiarr:
    image: golift/notifiarr:v0.9.5
    container_name: notifiarr
    hostname: notifiarr
    environment:
      - DN_API_KEY=${DN_API_KEY}
      - DN_UI_PASSWORD=${DN_UI_PASSWORD}
    volumes:
      - /home/tim/config/notifiarr:/config
      - /var/run/utmp:/var/run/utmp
      - /etc/machine-id:/etc/machine-id
    expose:
      - 5454
    networks:
      - media-net
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped

  speedtest-tracker:
    image: linuxserver/speedtest-tracker:1.14.2
    container_name: speedtest-tracker
    hostname: speedtest-tracker
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Amsterdam
      - MAIL_HOST=${SPEEDTEST_MAIL_HOST}
      - MAIL_PORT=${SPEEDTEST_MAIL_PORT}
      - MAIL_USERNAME=${SPEEDTEST_MAIL_USERNAME}
      - MAIL_PASSWORD=${SPEEDTEST_MAIL_PASSWORD}
      - MAIL_ENCRYPTION=${SPEEDTEST_MAIL_ENCRYPTION}
      - MAIL_FROM_ADDRESS=${SPEEDTEST_MAIL_FROM_ADDRESS}
      - APP_KEY=${SPEEDTEST_APP_KEY}
      - DB_CONNECTION=sqlite
      - SPEEDTEST_SCHEDULE="0 */6 * * *"
      - SPEEDTEST_SERVERS="49730,61186"
      - PRUNE_RESULTS_OLDER_THAN=120
    volumes:
      - /home/tim/config/speedtest:/config
    expose:
      - 80
    networks:
      - monitoring-net
      - proxy-net
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped

networks:
  proxy-net:
    driver: bridge
  media-net:
    driver: bridge
  monitoring-net:
    driver: bridge
  wg:
    driver: bridge
    enable_ipv6: true
    ipam:
      driver: default
      config:
        - subnet: 10.42.42.0/24
        - subnet: fdcc:ad94:bacf:61a3::/64
